#!/bin/bash -l
#PBS -N int_circ
#PBS -A UMEL0003
#PBS -j oe
#PBS -k eod
#PBS -q regular
#PBS -m abe
#PBS -M galen@stat.cmu.edu
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=36

### Set temp to scratch
export TMPDIR=/glade/scratch/$USER/temp
mkdir -p $TMPDIR

### Run Program
module purge
module load ncarenv gnu/9.1.0 ncarcompilers python/3.7.9
ncar_pylib windshear_npl_clone

python3 integrated_circulation.py
